// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * โ–โ–โ–โ–โ–โ–โ–โ–โ•—โ–โ–โ•—   โ–โ–โ•—โ–โ–โ–โ–โ–โ–โ–โ•—โ–โ–โ–โ•—   โ–โ–โ–โ•—  V2
  *    โ–โ–โ•”โ•โ•โ•โ•โ–โ–โ•— โ–โ–โ•”โ•โ–โ–โ•”โ•โ•โ•โ•โ•โ–โ–โ–โ–โ•— โ–โ–โ–โ–โ•‘
   *    โ–โ–โ•‘    โ•โ–โ–โ–โ–โ•”โ• โ–โ–โ–โ–โ–โ–โ–โ•—โ–โ–โ•”โ–โ–โ–โ–โ•”โ–โ–โ•‘
    *    โ–โ–โ•‘     โ•โ–โ–โ•”โ•  โ•โ•โ•โ•โ•โ–โ–โ•‘โ–โ–โ•‘โ•โ–โ–โ•”โ•โ–โ–โ•‘
     *    โ–โ–โ•‘      โ–โ–โ•‘   โ–โ–โ–โ–โ–โ–โ–โ•‘โ–โ–โ•‘ โ•โ•โ• โ–โ–โ•‘
      *
       * @title   TYSM Daily Faucet V2
        * @author  tops87
         * @notice  เธฃเธฐเธเธ Milestone Reward 7/15/30 เธงเธฑเธ
          *
           * Reward Schedule:
            * เธงเธฑเธเธ—เธตเน 1-6   โ’ 2,000 TYSM
             * เธงเธฑเธเธ—เธตเน 7     โ’ 10,000 TYSM ๐
              * เธงเธฑเธเธ—เธตเน 8-14  โ’ 2,000 TYSM
               * เธงเธฑเธเธ—เธตเน 15    โ’ 40,000 TYSM ๐๐
                * เธงเธฑเธเธ—เธตเน 16-29 โ’ 2,000 TYSM
                 * เธงเธฑเธเธ—เธตเน 30    โ’ 90,000 TYSM ๐๐๐
                  * เธงเธฑเธเธ—เธตเน 31+   โ’ Reset โ’ Cycle เนเธซเธกเน
                   */

                   interface IERC20 {
                       function transfer(address to, uint256 amount) external returns (bool);
                           function balanceOf(address account) external view returns (uint256);
                           }

                           contract TYSMFaucetV2 {

                               // =========================================================
                                   //  STATE
                                       // =========================================================

                                           IERC20 public immutable tysm;
                                               address public owner;

                                                   uint256 public baseReward       = 2_000  * 10**18;
                                                       uint256 public milestone7Reward = 10_000 * 10**18;
                                                           uint256 public milestone15Reward= 40_000 * 10**18;
                                                               uint256 public milestone30Reward= 90_000 * 10**18;
                                                                   uint256 public cooldown         = 24 hours;

                                                                       struct UserInfo {
                                                                               uint256 lastClaim;    // timestamp เธเธฃเธฑเนเธเธฅเนเธฒเธชเธธเธ”
                                                                                       uint256 streak;       // เธงเธฑเธเธ•เธดเธ”เธ•เนเธญเธเธฑเธเนเธเธฃเธญเธเธเธฑเธเธเธธเธเธฑเธ (1-30)
                                                                                               uint256 totalClaimed; // เธฃเธงเธกเธ—เธฑเนเธเธซเธกเธ” (wei)
                                                                                                       uint256 totalDays;    // เธงเธฑเธเธฃเธงเธกเธ—เธฑเนเธเธซเธกเธ”เธ—เธตเนเน€เธเธข Claim (เนเธกเน reset)
                                                                                                           }

                                                                                                               mapping(address => UserInfo) public userInfo;
                                                                                                                   uint256 public totalClaimsCount;

                                                                                                                       // =========================================================
                                                                                                                           //  EVENTS
                                                                                                                               // =========================================================

                                                                                                                                   event Claimed(address indexed user, uint256 amount, uint256 streak, uint256 totalDays);
                                                                                                                                       event Withdrawn(address indexed owner, uint256 amount);
                                                                                                                                           event RewardsUpdated(uint256 base, uint256 m7, uint256 m15, uint256 m30);

                                                                                                                                               // =========================================================
                                                                                                                                                   //  CONSTRUCTOR
                                                                                                                                                       // =========================================================

                                                                                                                                                           constructor(address _tysm) {
                                                                                                                                                                   tysm  = IERC20(_tysm);
                                                                                                                                                                           owner = msg.sender;
                                                                                                                                                                               }

                                                                                                                                                                                   modifier onlyOwner() {
                                                                                                                                                                                           require(msg.sender == owner, "Not owner");
                                                                                                                                                                                                   _;
                                                                                                                                                                                                       }

                                                                                                                                                                                                           // =========================================================
                                                                                                                                                                                                               //  REWARD CALCULATOR
                                                                                                                                                                                                                   // =========================================================

                                                                                                                                                                                                                       /**
                                                                                                                                                                                                                            * @notice เธเธณเธเธงเธ“เธฃเธฒเธเธงเธฑเธฅเธ•เธฒเธก Streak เธเธฑเธเธเธธเธเธฑเธ
                                                                                                                                                                                                                                 * @param streak เธเธณเธเธงเธเธงเธฑเธเธ•เธดเธ”เธ•เนเธญเธเธฑเธ (1-30)
                                                                                                                                                                                                                                      */
                                                                                                                                                                                                                                          function calculateReward(uint256 streak) public view returns (uint256) {
                                                                                                                                                                                                                                                  if (streak == 30) return milestone30Reward; // ๐๐๐ 90,000
                                                                                                                                                                                                                                                          if (streak == 15) return milestone15Reward; // ๐๐ 40,000
                                                                                                                                                                                                                                                                  if (streak == 7)  return milestone7Reward;  // ๐ 10,000
                                                                                                                                                                                                                                                                          return baseReward;                           // 2,000
                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                  // =========================================================
                                                                                                                                                                                                                                                                                      //  CLAIM
                                                                                                                                                                                                                                                                                          // =========================================================

                                                                                                                                                                                                                                                                                              function claim() external {
                                                                                                                                                                                                                                                                                                      UserInfo storage user = userInfo[msg.sender];

                                                                                                                                                                                                                                                                                                              require(
                                                                                                                                                                                                                                                                                                                          block.timestamp >= user.lastClaim + cooldown,
                                                                                                                                                                                                                                                                                                                                      "Come back in 24 hours!"
                                                                                                                                                                                                                                                                                                                                              );

                                                                                                                                                                                                                                                                                                                                                      // เธเธณเธเธงเธ“ Streak
                                                                                                                                                                                                                                                                                                                                                              if (user.lastClaim > 0 && block.timestamp <= user.lastClaim + 48 hours) {
                                                                                                                                                                                                                                                                                                                                                                          user.streak++;
                                                                                                                                                                                                                                                                                                                                                                                  } else {
                                                                                                                                                                                                                                                                                                                                                                                              user.streak = 1;
                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                              // เธซเธฅเธฑเธ Day 30 โ’ Reset เน€เธเนเธ Cycle เนเธซเธกเน
                                                                                                                                                                                                                                                                                                                                                                                                                      if (user.streak > 30) {
                                                                                                                                                                                                                                                                                                                                                                                                                                  user.streak = 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                  uint256 reward = calculateReward(user.streak);

                                                                                                                                                                                                                                                                                                                                                                                                                                                          require(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      tysm.balanceOf(address(this)) >= reward,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  "Faucet empty! Please wait for refill."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  user.lastClaim    = block.timestamp;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          user.totalClaimed += reward;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  user.totalDays++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          totalClaimsCount++;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  require(tysm.transfer(msg.sender, reward), "Transfer failed");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          emit Claimed(msg.sender, reward, user.streak, user.totalDays);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // =========================================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      //  VIEW FUNCTIONS
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // =========================================================

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              function getTimeLeft(address _user) external view returns (uint256) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      UserInfo memory user = userInfo[_user];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (block.timestamp >= user.lastClaim + cooldown) return 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return (user.lastClaim + cooldown) - block.timestamp;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              function canClaim(address _user) external view returns (bool) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return block.timestamp >= userInfo[_user].lastClaim + cooldown;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              function faucetBalance() external view returns (uint256) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return tysm.balanceOf(address(this));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              /// @notice เธฃเธฒเธเธงเธฑเธฅเธ—เธตเนเธเธฐเนเธ”เนเนเธเธเธฒเธฃ Claim เธเธฃเธฑเนเธเธ–เธฑเธ”เนเธ
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  function nextReward(address _user) external view returns (uint256) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          uint256 streak = userInfo[_user].streak;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  uint256 next   = streak + 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (next > 30) next = 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return calculateReward(next);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          /// @notice เธงเธฑเธเธ—เธตเนเน€เธซเธฅเธทเธญเนเธเธ–เธถเธ Milestone เธ–เธฑเธ”เนเธ
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              function daysToNextMilestone(address _user) external view returns (uint256 daysLeft, uint256 milestoneDay, uint256 milestoneReward) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      uint256 streak = userInfo[_user].streak;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (streak < 7)  return (7 - streak,  7,  milestone7Reward);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (streak < 15) return (15 - streak, 15, milestone15Reward);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (streak < 30) return (30 - streak, 30, milestone30Reward);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return (0, 30, milestone30Reward);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // =========================================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  //  OWNER FUNCTIONS
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      // =========================================================

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          function withdrawAll() external onlyOwner {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  uint256 bal = tysm.balanceOf(address(this));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          require(bal > 0, "Nothing to withdraw");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  tysm.transfer(owner, bal);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          emit Withdrawn(owner, bal);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  function setBaseReward(uint256 _amount) external onlyOwner {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          baseReward = _amount;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  emit RewardsUpdated(baseReward, milestone7Reward, milestone15Reward, milestone30Reward);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          function setMilestoneRewards(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  uint256 _day7,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          uint256 _day15,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  uint256 _day30
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ) external onlyOwner {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              milestone7Reward  = _day7;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      milestone15Reward = _day15;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              milestone30Reward = _day30;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      emit RewardsUpdated(baseReward, _day7, _day15, _day30);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              function setCooldown(uint256 _seconds) external onlyOwner {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      cooldown = _seconds;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              function transferOwnership(address _newOwner) external onlyOwner {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      require(_newOwner != address(0), "Zero address");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              owner = _newOwner;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
